version: '3.4'

services:
  apiblog:
    image: apiblog
    networks:
      - blog-pgsql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    container_name: apiblog
    depends_on:
      - dbpostgres
          
  dbpostgres:
    container_name: db_postgres
    image: postgres:latest
    networks:
      - blog-pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cardenascode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  blog-pgsql: